config/routes.rb
Rails.application.routes.draw do
  root :to => 'questions#index'

  resources :questions do
    resources :choices
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :question
  validates :choice, :presence => true
  after_initialize :init
  
  def init
    self.votes ||= 0
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :choices
  validates :question, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController

  def edit
    @choice = Choice.find(params[:id])
    @question = Question.find(params[:question_id])
    if @choice.update(votes: @choice.votes + 1)
      respond_to do |format|
        format.html { redirect_to questions_path() }
        format.js
      end
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/choices/_form.html.erb
<div class="col-md-6">
<%= render "layouts/errors", :object => @choice %>
  <%= form_for [@question, @choice], remote: true do |f| %>
  <div class="form-group">
    <%= f.label :choice %>
    <%= f.text_field :choice, class: 'form-control' %>
  </div>
    <%= f.submit class: 'btn btn-default' %>
  <% end %>

</div>

app/views/choices/create.js.erb
$(function() {
  $('#new_choice').remove();
  $('.new_choice_link').show();
  $('.choices').append('<h3><%= @choice.choice %></h3>');
})

app/views/choices/edit.js.erb
$(function() {
  $('#question<%= @question.id%>').children().children().show();
  $('#choice<%= @choice.id %>').children('.votes').html('<%= @choice.votes %>');
  $('#choice<%= @choice.id %>').attr('style', 'background-color:cornflowerblue;');
  $('#question<%= @question.id%>').children().children().contents().unwrap();
})

app/views/choices/new.html.erb
<h1>New Choice</h1>

<%= render 'form' %>

app/views/choices/new.js.erb
$(function() {
  $('.new_choice_link').hide().after('<%= j render "form" %>')
})

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ajax</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<div class="col-md-6">
  <%= render "layouts/errors", :object => @question %>

  <%= form_for @question, remote: true, id:'new_question_form' do |f| %>
  <div class="form-group">
    <%= f.label :question %>
    <%= f.text_field :question, class: 'form-control' %>
  </div>
  <%= f.submit class: 'btn btn-default' %>
  <% end %>
</div>

app/views/questions/_question.erb
<div class="col-md-4">
  <div id="question<%= question.id %>" class="panel">
    <h1> <%= question.question %> </h1>
    <% question.choices.each do |choice|%>
      <div id="choice<%= choice.id %>" class="col-md-6 choice">
        <%= link_to(edit_question_choice_path(question, choice), remote: true) do %>
        <p><%= choice.choice %></p>
        <% end %>
        <p class="votes"> </p>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/create.js.erb
$(function() {
  $('#new_question').remove();
  $('#new_question_link').show();
  $('#questions').append('<%= j render(@question) %>');
})

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= render 'form' %>

app/views/questions/edit.js.erb
$(function() {
  $('#edit_question_link_<%= @question.id %>').hide().after('<%= j render "form" %>');
})

app/views/questions/index.html.erb
<div class="row" id="questions">
  <% @questions.each do |question| %>
    <%= render 'question', :question => question %>
  <% end %>
</div>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

app/views/questions/new.js.erb
$(function() {
  $('#new_question_link').hide().after('<%= j render "form" %>')
})

app/views/questions/show.html.erb
<h1 id="question<%= @question.id %>"> <%= @question.question %> </h1>
<p><%= flash[:notice] %></p>
<div class="choices">
  <% @question.choices.each do |choice| %>
    <h3> <%= choice.choice %> </h3>
  <% end %>
</div>

app/views/questions/update.js.erb
$(function() {
  $('#edit_question_<%= @question.id %>').remove();
  $('#edit_question_link_<%= @question.id %>').show();
  $('#question<%= @question.id %>').html('<%= @question.question %>')
})